# Generated by Django 4.1.1 on 2022-09-19 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='clients',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
